import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
await mkdir('artifacts', { recursive: true });
const server = spawn(process.execPath, ['server.mjs'], { env: { ...process.env, PORT: '4187' }, stdio: 'pipe' });
await new Promise((resolve, reject) => { server.stdout.once('data', resolve); server.once('error', reject); });
let browser;
const results = [];
try {
  browser = await chromium.launch({ ...(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {}), headless: true, args: ['--no-sandbox', '--enable-webgl', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const context = await browser.newContext({ viewport: { width: 844, height: 390 }, hasTouch: true, isMobile: true, deviceScaleFactor: 1 });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', msg => { if (msg.type() === 'error') errors.push(msg.text()); });
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:4187', { waitUntil: 'networkidle' });
  await page.waitForFunction(() => window.__combat);
  await page.waitForFunction(() => window.__combat.snapshot().started);
  assert.equal(await page.locator('#welcome').isVisible(), false, 'no startup popup');
  assert.equal(await page.locator('iframe').count(), 0, 'direct document, no iframe');
  const gameBounds = await page.locator('#game').boundingBox();
  assert.equal(gameBounds.width, 844); assert.equal(gameBounds.height, 390);
  results.push('Starts directly with viewport-filling canvas and no startup popup or iframe');
  const snapshot = () => page.evaluate(() => window.__combat.snapshot());
  const advance = async seconds => {
    const until = (await snapshot()).simTime + seconds;
    await page.waitForFunction(time => window.__combat.snapshot().simTime >= time, until, { timeout: 15000 });
  };
  let before = await snapshot();
  assert.equal(before.view, 'isometric-v2');
  const target = before.targets[0];
  await page.mouse.move(target.screenX, target.screenY);
  await page.keyboard.down('Space');
  await advance(0.52); await page.keyboard.up('Space');
  let after = await snapshot(); assert.ok(after.shots >= 3); assert.ok(after.hits >= 3); results.push('Mouse aim and held fire hit real targets');
  await page.locator('#swap').click(); await advance(0.25);
  assert.equal((await snapshot()).weapon, 'PISTOL');
  await page.keyboard.down('Space'); await advance(0.08); await page.keyboard.up('Space');
  assert.equal((await snapshot()).ammo, 11);
  await page.locator('#reload').click(); assert.ok((await snapshot()).reloading > 0);
  await advance(1.05);
  assert.equal((await snapshot()).reloading, 0); assert.equal((await snapshot()).ammo, 12); results.push('Weapon switching and actual magazine reload through UI');
  await page.locator('#reset').click();
  const center = async id => { const b = await page.locator(id).boundingBox(); return { x: b.x + b.width / 2, y: b.y + b.height / 2 }; };
  const move = await center('#move'), aim = await center('#aim'), fire = await center('#fire-left');
  const cdp = await context.newCDPSession(page);
  const touch = (type, points) => cdp.send('Input.dispatchTouchEvent', { type, touchPoints: points.map(([id, x, y]) => ({ id, x, y, radiusX: 4, radiusY: 4, force: 1 })) });
  before = await snapshot();
  await touch('touchStart', [[1, move.x, move.y], [2, aim.x, aim.y], [3, fire.x, fire.y]]);
  await touch('touchMove', [[1, move.x + 40, move.y], [2, aim.x, aim.y - 40], [3, fire.x, fire.y]]);
  await advance(0.5);
  after = await snapshot(); assert.ok(after.x > before.x + 0.7 && after.z < before.z - 0.7); assert.ok(after.aimZ < -0.65 && after.aimX < -0.65); assert.ok(after.shots > before.shots); assert.equal(after.fireCount, 1);
  assert.ok(after.cameraX > before.cameraX && after.cameraZ < before.cameraZ, 'camera follows movement');
  assert.ok(Math.abs(after.playerScreenX - 422) < 50, 'player stays close to screen center');
  results.push('Three simultaneous fingers independently move, aim, and fire');
  await touch('touchEnd', []); await advance(0.18);
  const released = await snapshot(); assert.equal(released.fireCount, 0); assert.equal(released.move.x, 0); assert.equal(released.aim.y, 0);
  await advance(0.2); after = await snapshot(); assert.equal(after.shots, released.shots); assert.equal(after.x, released.x); results.push('Touch release stops movement and firing without stuck inputs');
  await page.locator('#mode').click();
  await touch('touchStart', [[2, aim.x, aim.y]]); await touch('touchMove', [[2, aim.x + 40, aim.y]]); await advance(0.35);
  assert.ok((await snapshot()).shots > after.shots);
  await touch('touchCancel', []); await advance(0.16); assert.equal((await snapshot()).aim.x, 0); results.push('Two-thumb aim-and-fire and cancellation');
  await page.screenshot({ path: 'artifacts/landscape.png' });
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(150);
  for (const id of ['#move', '#aim', '#fire-right', '#reload', '#swap']) { const b = await page.locator(id).boundingBox(); assert.ok(b.x >= 0 && b.y >= 0 && b.x + b.width <= 391 && b.y + b.height <= 845, id + ' within portrait viewport'); }
  await page.screenshot({ path: 'artifacts/portrait.png' });
  assert.deepEqual(errors, []); results.push('Landscape/portrait UI fits; no runtime or console errors');
  await writeFile('artifacts/browser-result.json', JSON.stringify({ pass: true, results, snapshot: await snapshot() }, null, 2));
  console.log(JSON.stringify({ pass: true, results }, null, 2));
} finally { if (browser) await browser.close(); server.kill(); }
